### ISSUE TITLE
Uncaught exception stacktrace

### ISSUE THREAD

**Issue by jpopelka** [gluetool/gluetool#46]
When an uncaught exception happens only the exception string is print out.
The whole stacktrace can be seen only in debug mode.

Can the whole stack be visible even in a non-debug mode ?

My point of view is that this is something that I see only one time before the program crashes, so not something to worry about polluting the 'normal' output.

**Comment by happz** [comment]
TBH, I'd rather not display complete stack trace on stderr when not in a debug mode, at least not by default. We're using `gluetool` with `-o` switch, logging all `DEBUG` messages into a file, including full stack traces, keeping our stdout's nice and clean while giving us all info we'd need for a post-mortem. Would this be a feasible solution for your problem?

**Comment by thrix** [comment]
@happz after discussion would be nice if we could, with some special option (--show-traceback) enable just traceback print out in non-debug mode. This would suffice for the reporter. They like the information logs, but would like to see a full traceback in case it fails, instead of just the traceback message string. Note that they are running gluetool in openshift and this would make the console log better for them.

**Comment by happz** [comment]
That's fine with me, an option to enable tracebacks on stderr is my preferred solution, and it can be enabled in a config file without the need to specify it every time one runs gluetool.

**Comment by happz** [comment]
Implemented in #48.
